### ISSUE TITLE
Input coordinates for 3D

### ISSUE THREAD

**Issue by iamSHAN98** [Duke-QCD/frzout#2]
Are the input coordinates supposed to be Cartesian only? I mean in (3+1) D hydro one uses (tau, x, y, eta_s). I am using 
**Cornelius** for finding the hypersurface. Is the Cornelius output to be put directly in **frzout** ?

**Comment by jbernhard** [comment]
The input coordinates are expected to be Cartesian (t, x, y, z). Other coordinate systems must be converted first. I am not sure what Cornelius generates.

See [the docs](http://qcd.phy.duke.edu/frzout/usage.html) for complete information.
